apiVersion: v1alpha1
kind: Setting
metadata:
  name: chenhe-lsky-pro-settings
spec:
  forms:
    - group: basic
      label: ä½¿ç”¨æç¤º
      formSchema:
        - $el: 'p'
          attrs:
            style: { padding: '4px 0' }
          children: "æ­¤å¤„æ— éœ€è®¾ç½®ï¼Œè¯·å‰å¾€ ã€Œé™„ä»¶ - å­˜å‚¨ç­–ç•¥ã€æ·»åŠ ç­–ç•¥ã€‚"

        - $el: 'a'
          attrs:
            href: "https://github.com/ichenhe/halo-lsky-pro#readme"
            target: "_blank"
            style: { display: 'block', padding: '4px 0'}
          children: "ğŸ“– è¯¦ç»†ä½¿ç”¨è¯´æ˜ [ç‚¹å‡»è·³è½¬]"

        - $el: 'a'
          attrs:
            href: "https://github.com/ichenhe/halo-lsky-pro/issues"
            target: "_blank"
            style: { display: 'block', padding: '4px 0' }
          children: "ğŸ¤” é—®é¢˜åé¦ˆ / å¯»æ±‚å¸®åŠ©è¯·å‰å¾€ GitHub issues [ç‚¹å‡»è·³è½¬]"